#!/usr/bin/python3

import sys
import os
import glob
import os.path
import tkinter as tk
from PIL import Image, ImageTk
import webbrowser

page1 = 1
page2 = 0
nbSecure = 0
nbPhishing = 0

def Page1(null):
    main_menu = Image.open("assets/main_menu.png")
    main_menu = ImageTk.PhotoImage(main_menu)
    main_menu_label = tk.Label(image=main_menu, borderwidth=0)
    main_menu_label.image = main_menu
    main_menu_label.pack()
    main_menu_label.place(x=385, y=44)

    img_scan = Image.open("assets/scan_butt.png")
    img_scan = ImageTk.PhotoImage(img_scan)
    img_scan_label = tk.Label(image=img_scan, borderwidth=0)
    img_scan_label.image = img_scan
    img_scan_label.pack()
    img_scan_label.bind("<Button-1>", scanning)
    img_scan_label.place(x=684, y=594)

    img_details = Image.open("assets/details_butt.png")
    img_details = ImageTk.PhotoImage(img_details)
    img_details_label = tk.Label(image=img_details, borderwidth=0)
    img_details_label.image = img_details
    img_details_label.pack()
    img_details_label.bind("<Button-1>", details)
    img_details_label.place(x=972, y=594)
    page1 = 1
    page2 = 0

def Page2(null):
    result = Image.open("assets/result.png")
    result = ImageTk.PhotoImage(result)
    result_label = tk.Label(image=result, borderwidth=0)
    result_label.image = result
    result_label.pack()
    result_label.place(x=385, y=44)
    page1 = 0
    page2 = 1

def scanning(null):
    print("Scanning")
    folderpath = "./mails"
    if os.path.exists(folderpath) != 1:
        print("Please create a folder named 'mails' and add each file.eml you want check")
        sys.exit(84)
    mailsContent = [mail for mail in glob.glob("./mails/*.eml")]
    print(mailsContent)
    for m in mailsContent:
        print(m)
        nbPhishing = 1
        nbSecure = 1

def details(null):
    webbrowser.open('https://github.com/AntoineGsr/GoC-2022')

def main():
    print("App launched")
    root = tk.Tk()
    root.wm_geometry("1589x868")
    root.title("EPYPHISH - GoC 2022")

    background = Image.open("assets/background.png")
    background = ImageTk.PhotoImage(background)
    background_label = tk.Label(image=background)
    background_label.image = background
    background_label.place(x=0, y=0)

    home = Image.open("assets/home_butt.png")
    home = ImageTk.PhotoImage(home)
    home_label = tk.Label(image=home, borderwidth=0)
    home_label.image = home
    home_label.pack()
    home_label.bind("<Button-1>", Page1)
    home_label.place(x=131, y=239)

    result = Image.open("assets/result_butt.png")
    result = ImageTk.PhotoImage(result)
    result_label = tk.Label(image=result, borderwidth=0)
    result_label.image = result
    result_label.pack()
    result_label.bind("<Button-1>", Page2)
    result_label.place(x=131, y=325)
    if page1 == 1:
        Page1("null")
    else:
        Page2("null")

    root.mainloop()

if __name__ == '__main__':
    sys.exit(main())
