#!/usr/bin/python3
import tkinter as tk


class MainView(tk.Frame):
    def __init__(self, parent, *args, **kwargs):
        super().__init__(parent, *args, **kwargs)

        container = tk.Frame(self)
        container.pack(side='top', fill='both', expand=True)

        # Create dictionary of page (Frame subclass) instances.
        self.pages  = {}
        for Page in (Home, Bullying, Abuse, Other):
            page = Page(container, controller=self)
            self.pages[Page.__name__] = page
            page.place(in_=container, x=0, y=0, relwidth=1, relheight=1)

        menubar = tk.Menu(parent)
        filemenu = tk.Menu(menubar, tearoff=0)

        def options(page_name, show=self.show):  # Helper func.
            return dict(label=page_name, command=lambda: show(page_name))

        filemenu.add_command(**options('Home'))
        filemenu.add_command(**options('Bullying'))
        filemenu.add_command(**options('Abuse'))
        filemenu.add_command(**options('Other'))

        filemenu.add_separator()
        filemenu.add_command(label='Quit', command=exit)
        menubar.add_cascade(label='Navigate', menu=filemenu)

        parent.config(menu=menubar)
        self.show('Home')  # Display initial page.

    def show(self, page_name):
        self.pages[page_name].lift()


class Home(tk.Frame):
   def __init__(self, parent, controller):
       super().__init__(parent)

       label = tk.Label(self, text='Welcome to the Help Hotline! '
                                   'Please select your concern.', relief='groove')
       label.grid(row=0, column=1, columnspan=3, sticky='nesw', padx=5, pady=5)

       def options(page_name, show=controller.show):  # Helper func.
           return dict(text=page_name, command=lambda: show(page_name))

       bully_button = tk.Button(self, **options('Bullying'))
       bully_button.grid(row = 1, column=1, padx=5, pady=5, sticky='nsew')

       abuse_button = tk.Button(self, **options('Abuse'))
       abuse_button.grid(row=1, column=2, padx=5, pady=5, sticky='nsew')

       other_button = tk.Button(self, **options('Other'))
       other_button.grid(row=1, column=3, padx=5, pady=5, sticky='nsew')


class Bullying(tk.Frame):
   def __init__(self, parent, controller):
       super().__init__(parent)

       label = tk.Label(self, text='This is page 2')
       label.grid(row=0, column=1, sticky='nesw', padx=5, pady=5)


class Abuse(tk.Frame):
   def __init__(self, parent, controller):
       super().__init__(parent)

       label = tk.Label(self, text='This is page 3')
       label.grid(row=0, column=1, sticky='nesw', padx=5, pady=5)


class Other(tk.Frame):
   def __init__(self, parent, controller):
       super().__init__(parent)

       label = tk.Label(self, text='This is page 4')
       label.grid(row=0, column=1, sticky='nesw', padx=5, pady=5)


root = tk.Tk()
root.geometry('500x500')
main = MainView(root)
main.pack(side='top', fill='both', expand=True)
root.title('Bullying and Abuse Hotline')
root.mainloop()